ecpay.merchant_id=3002607
ecpay.hash_key=pwFHCqoQZGmho4w6
ecpay.hash_iv=EkRm7iFT261dpevs
# 這是上 Zeabur 時使用的網域 (請根據你的實際專案替換)
ecpay.return_url=https://your-domain.zeabur.app/checkout/ecpay/callback
ecpay.order_result_url_base=https://your-domain.zeabur.app/checkout/ecpay/return